# Generated by Django 5.2.8 on 2025-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField()),
                ('published_at', models.DateField()),
            ],
        ),
    ]
